"""The Bridges-2 runbook's hard stops, exercised against real git repos.

The incident these guard: `git pull` aborted (a tracked report had local changes
from a previous run), HEAD stayed on an old commit, the hash check printed the
mismatch -- and the sbatch lines ran anyway, so both jobs ran the wrong code. A
check that only works when a human is reading the output fails exactly when they
are moving fast, so every check here must stop the script, not just print.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

SCRIPTS = Path("scripts/bridges2").resolve()
ENV = {
    **os.environ,
    "GIT_AUTHOR_NAME": "t",
    "GIT_AUTHOR_EMAIL": "t@t",
    "GIT_COMMITTER_NAME": "t",
    "GIT_COMMITTER_EMAIL": "t@t",
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
}


def git(cwd: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True, env=ENV
    )
    return out.stdout.strip()


def commit(repo: Path, name: str, text: str) -> str:
    (repo / name).parent.mkdir(parents=True, exist_ok=True)
    (repo / name).write_text(text)
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", f"add {name}")
    return git(repo, "rev-parse", "HEAD")


@pytest.fixture
def cluster(tmp_path):
    """origin (bare) at H2, a laptop clone that pushed both commits, and a
    'cluster' clone that only ever pulled H1 -- the stale checkout."""
    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True, env=ENV)
    laptop = tmp_path / "laptop"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(laptop)], check=True, env=ENV, capture_output=True
    )
    git(laptop, "checkout", "-q", "-b", "main")
    # The job runs assert_commit.sh from inside the checkout it verifies, so a
    # real checkout contains it; the fake one must too.
    (laptop / "scripts/bridges2").mkdir(parents=True)
    (laptop / "scripts/bridges2/assert_commit.sh").write_text(
        (SCRIPTS / "assert_commit.sh").read_text()
    )
    h1 = commit(laptop, "reports/eval.md", "v1\n")
    git(laptop, "push", "-q", "origin", "main")
    stale = tmp_path / "stale"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(stale)], check=True, env=ENV, capture_output=True
    )
    h2 = commit(laptop, "code.py", "print(2)\n")
    git(laptop, "push", "-q", "origin", "main")
    return {
        "stale": stale,
        "h1": h1,
        "h2": h2,
        "calls": tmp_path / "sbatch_calls.txt",
        "tmp": tmp_path,
    }


def stub_sbatch(tmp: Path, calls: Path) -> Path:
    stub = tmp / "sbatch"
    stub.write_text(f'#!/bin/bash\necho "$@" >> {calls}\n')
    stub.chmod(0o755)
    return stub


def run_submit(cluster, expected: str | None):
    stub = stub_sbatch(cluster["tmp"], cluster["calls"])
    args = ["bash", str(SCRIPTS / "submit.sh")] + ([expected] if expected else [])
    env = {**ENV, "LEDGERQL_REPO": str(cluster["stale"]), "SBATCH": str(stub)}
    return subprocess.run(args, capture_output=True, text=True, env=env)


def sbatch_calls(cluster) -> list[str]:
    return cluster["calls"].read_text().splitlines() if cluster["calls"].exists() else []


def test_submit_stops_before_sbatch_when_a_tracked_file_blocks_the_pull(cluster):
    # THE INCIDENT: a previous run left reports/eval.md modified; pull aborts.
    (cluster["stale"] / "reports/eval.md").write_text("regenerated by an old run\n")
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []  # nothing was submitted
    assert "reports/eval.md" in result.stderr
    assert "git checkout -- reports/eval.md" in result.stderr  # the recovery command
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h1"]  # untouched


def test_submit_stops_before_sbatch_when_head_is_not_the_expected_commit(cluster):
    wrong = "0" * 40
    result = run_submit(cluster, wrong)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "MISMATCH" in result.stderr and "git pull" in result.stderr


def test_submit_pulls_verifies_and_submits_both_jobs_pinned_to_the_commit(cluster):
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode == 0, result.stderr
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h2"]
    calls = sbatch_calls(cluster)
    assert len(calls) == 2
    assert all(f"EXPECTED_COMMIT={cluster['h2']}" in c for c in calls)
    assert any("30b" in c for c in calls) and any("32b" in c for c in calls)


def test_submit_refuses_to_run_without_an_expected_commit(cluster):
    result = run_submit(cluster, None)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "usage" in result.stderr.lower()  # refused for the right reason


def test_submit_refuses_an_abbreviated_hash(cluster):
    # A short prefix could match the wrong commit; the runbook needs all 40.
    result = run_submit(cluster, cluster["h2"][:7])
    assert result.returncode != 0 and sbatch_calls(cluster) == []
    assert "40" in result.stderr


def test_assert_commit_passes_only_on_the_exact_clean_commit(cluster):
    repo = cluster["stale"]
    ok = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert ok.returncode == 0 and cluster["h1"] in ok.stdout
    (repo / "reports/eval.md").write_text("dirty\n")
    dirty = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert dirty.returncode != 0 and "reports/eval.md" in dirty.stderr


def test_the_job_itself_refuses_to_start_without_or_on_the_wrong_commit(cluster, tmp_path):
    # Belt and braces: even if someone runs sbatch by hand and skips submit.sh,
    # the job must refuse. Guard runs before any module load / GPU work.
    home = tmp_path / "home"
    (home / "ledgerql-bridges2").mkdir(parents=True)
    (home / "ledgerql-bridges2" / "ledgerql").symlink_to(cluster["stale"])
    script = [str(SCRIPTS / "run_model_eval.sh"), "some/model", "1"]
    env = {**ENV, "HOME": str(home)}
    env.pop("EXPECTED_COMMIT", None)
    missing = subprocess.run(["bash", *script], capture_output=True, text=True, env=env)
    assert missing.returncode != 0 and "EXPECTED_COMMIT" in missing.stderr
    wrong = subprocess.run(
        ["bash", *script], capture_output=True, text=True, env={**env, "EXPECTED_COMMIT": "0" * 40}
    )
    assert wrong.returncode != 0 and "MISMATCH" in wrong.stderr
    right = subprocess.run(
        ["bash", *script],
        capture_output=True,
        text=True,
        env={**env, "EXPECTED_COMMIT": cluster["h1"]},
    )
    assert "commit verified" in right.stdout  # got past the guard (then fails on module load)
