"""The Bridges-2 runbook's hard stops, exercised against real git repos.

The incident these guard: `git pull` aborted (a tracked report had local changes
from a previous run), HEAD stayed on an old commit, the hash check printed the
mismatch -- and the sbatch lines ran anyway, so both jobs ran the wrong code. A
check that only works when a human is reading the output fails exactly when they
are moving fast, so every check here must stop the script, not just print.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

SCRIPTS = Path("scripts/bridges2").resolve()
ENV = {
    **os.environ,
    "GIT_AUTHOR_NAME": "t",
    "GIT_AUTHOR_EMAIL": "t@t",
    "GIT_COMMITTER_NAME": "t",
    "GIT_COMMITTER_EMAIL": "t@t",
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
}


def git(cwd: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True, env=ENV
    )
    return out.stdout.strip()


def commit(repo: Path, name: str, text: str) -> str:
    (repo / name).parent.mkdir(parents=True, exist_ok=True)
    (repo / name).write_text(text)
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", f"add {name}")
    return git(repo, "rev-parse", "HEAD")


@pytest.fixture
def cluster(tmp_path):
    """origin (bare) at H2, a laptop clone that pushed both commits, and a
    'cluster' clone that only ever pulled H1 -- the stale checkout."""
    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True, env=ENV)
    laptop = tmp_path / "laptop"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(laptop)], check=True, env=ENV, capture_output=True
    )
    git(laptop, "checkout", "-q", "-b", "main")
    # The job runs assert_commit.sh from inside the checkout it verifies, so a
    # real checkout contains it; the fake one must too.
    (laptop / "scripts/bridges2").mkdir(parents=True)
    (laptop / "scripts/bridges2/assert_commit.sh").write_text(
        (SCRIPTS / "assert_commit.sh").read_text()
    )
    for job in SCRIPTS.glob("*.sbatch"):  # submit.sh refuses a job file the checkout lacks
        (laptop / "scripts/bridges2" / job.name).write_text(job.read_text())
    h1 = commit(laptop, "reports/eval.md", "v1\n")
    git(laptop, "push", "-q", "origin", "main")
    stale = tmp_path / "stale"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(stale)], check=True, env=ENV, capture_output=True
    )
    h2 = commit(laptop, "code.py", "print(2)\n")
    git(laptop, "push", "-q", "origin", "main")
    return {
        "stale": stale,
        "h1": h1,
        "h2": h2,
        "calls": tmp_path / "sbatch_calls.txt",
        "tmp": tmp_path,
    }


def stub_sbatch(tmp: Path, calls: Path) -> Path:
    stub = tmp / "sbatch"
    stub.write_text(f'#!/bin/bash\necho "$@" >> {calls}\n')
    stub.chmod(0o755)
    return stub


def run_submit(cluster, expected: str | None, *jobs: str):
    stub = stub_sbatch(cluster["tmp"], cluster["calls"])
    args = ["bash", str(SCRIPTS / "submit.sh")] + ([expected, *jobs] if expected else [])
    env = {**ENV, "LEDGERQL_REPO": str(cluster["stale"]), "SBATCH": str(stub)}
    return subprocess.run(args, capture_output=True, text=True, env=env)


def sbatch_calls(cluster) -> list[str]:
    return cluster["calls"].read_text().splitlines() if cluster["calls"].exists() else []


def test_submit_stops_before_sbatch_when_a_tracked_file_blocks_the_pull(cluster):
    # THE INCIDENT: a previous run left reports/eval.md modified; pull aborts.
    (cluster["stale"] / "reports/eval.md").write_text("regenerated by an old run\n")
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []  # nothing was submitted
    assert "reports/eval.md" in result.stderr
    assert "git checkout -- reports/eval.md" in result.stderr  # the recovery command
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h1"]  # untouched


def test_submit_stops_before_sbatch_when_head_is_not_the_expected_commit(cluster):
    wrong = "0" * 40
    result = run_submit(cluster, wrong)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "MISMATCH" in result.stderr and "git pull" in result.stderr


def test_submit_pulls_verifies_and_submits_both_jobs_pinned_to_the_commit(cluster):
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode == 0, result.stderr
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h2"]
    calls = sbatch_calls(cluster)
    assert len(calls) == 2
    assert all(f"EXPECTED_COMMIT={cluster['h2']}" in c for c in calls)
    assert any("30b" in c for c in calls) and any("32b" in c for c in calls)


def test_submit_takes_an_explicit_job_list_and_pins_each_to_the_commit(cluster):
    stale = cluster["stale"]
    laptop_job = "run_bakeoff_a.sbatch"
    # The job files must exist in the pulled commit, so add them upstream first.
    origin = git(stale, "remote", "get-url", "origin")
    laptop = cluster["tmp"] / "laptop"
    for name in (laptop_job, "run_bakeoff_b.sbatch"):
        h = commit(laptop, f"scripts/bridges2/{name}", "#!/bin/bash\n")
    git(laptop, "push", "-q", origin, "main")
    result = run_submit(cluster, h, laptop_job, "run_bakeoff_b.sbatch")
    assert result.returncode == 0, result.stderr
    calls = sbatch_calls(cluster)
    assert len(calls) == 2
    assert all(f"EXPECTED_COMMIT={h}" in c for c in calls)
    assert calls[0].endswith(laptop_job) and calls[1].endswith("run_bakeoff_b.sbatch")


def test_submit_submits_nothing_if_any_named_job_file_is_missing(cluster):
    # One typo must not leave the first job submitted and the second not.
    result = run_submit(cluster, cluster["h2"], "run_does_not_exist.sbatch")
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "run_does_not_exist.sbatch" in result.stderr


def test_submit_refuses_to_run_without_an_expected_commit(cluster):
    result = run_submit(cluster, None)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "usage" in result.stderr.lower()  # refused for the right reason


def test_submit_refuses_an_abbreviated_hash(cluster):
    # A short prefix could match the wrong commit; the runbook needs all 40.
    result = run_submit(cluster, cluster["h2"][:7])
    assert result.returncode != 0 and sbatch_calls(cluster) == []
    assert "40" in result.stderr


def test_assert_commit_passes_only_on_the_exact_clean_commit(cluster):
    repo = cluster["stale"]
    ok = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert ok.returncode == 0 and cluster["h1"] in ok.stdout
    (repo / "reports/eval.md").write_text("dirty\n")
    dirty = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert dirty.returncode != 0 and "reports/eval.md" in dirty.stderr


def test_the_job_itself_refuses_to_start_without_or_on_the_wrong_commit(cluster, tmp_path):
    # Belt and braces: even if someone runs sbatch by hand and skips submit.sh,
    # the job must refuse. Guard runs before any module load / GPU work.
    home = tmp_path / "home"
    (home / "ledgerql-bridges2").mkdir(parents=True)
    (home / "ledgerql-bridges2" / "ledgerql").symlink_to(cluster["stale"])
    script = [str(SCRIPTS / "run_model_eval.sh"), "some/model", "1"]
    env = {**ENV, "HOME": str(home)}
    env.pop("EXPECTED_COMMIT", None)
    missing = subprocess.run(["bash", *script], capture_output=True, text=True, env=env)
    assert missing.returncode != 0 and "EXPECTED_COMMIT" in missing.stderr
    wrong = subprocess.run(
        ["bash", *script], capture_output=True, text=True, env={**env, "EXPECTED_COMMIT": "0" * 40}
    )
    assert wrong.returncode != 0 and "MISMATCH" in wrong.stderr
    right = subprocess.run(
        ["bash", *script],
        capture_output=True,
        text=True,
        env={**env, "EXPECTED_COMMIT": cluster["h1"]},
    )
    assert "commit verified" in right.stdout  # got past the guard (then fails on module load)


GENONLY_JOBS = {
    "run_qwen3_coder_30b_genonly.sbatch": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "run_qwen25_coder_32b_awq_genonly.sbatch": "Qwen/Qwen2.5-Coder-32B-Instruct-AWQ",
    "run_xiyansql_32b_genonly.sbatch": "XGenerationLab/XiYanSQL-QwenCoder-32B-2504",
    "run_omnisql_32b_genonly.sbatch": "seeklhy/OmniSQL-32B",
}


def test_every_bridges2_script_parses():
    for script in [*SCRIPTS.glob("*.sh"), *SCRIPTS.glob("*.sbatch")]:
        result = subprocess.run(["bash", "-n", str(script)], capture_output=True, text=True)
        assert result.returncode == 0, f"{script.name}: {result.stderr}"


@pytest.mark.parametrize("job,repo_id", GENONLY_JOBS.items())
def test_each_bakeoff_job_runs_the_generation_only_mode_for_its_model(job, repo_id):
    text = (SCRIPTS / job).read_text()
    assert "export EVAL_MODE=gen_only" in text
    assert "export PROFILES=" in text
    assert f"run_model_eval.sh {repo_id} 1" in text
    assert "--gres=gpu:h100-80:1" in text  # H100-80 (docs/bridges2.md), not the V100 pool


def test_a_bakeoff_model_runs_its_own_native_profile_first_so_the_smoke_tests_it():
    def profiles(job):
        line = next(
            line for line in (SCRIPTS / job).read_text().splitlines() if "export PROFILES=" in line
        )
        return line.split("=", 1)[1].strip('"').split()

    assert profiles("run_xiyansql_32b_genonly.sbatch")[0] == "xiyan"
    assert profiles("run_omnisql_32b_genonly.sbatch")[0] == "omnisql"
    for job in ("run_qwen3_coder_30b_genonly.sbatch", "run_qwen25_coder_32b_awq_genonly.sbatch"):
        assert profiles(job)[0] == "current"
    assert all(set(profiles(j)) == {"current", "xiyan", "omnisql"} for j in GENONLY_JOBS)


def test_the_job_body_smoke_tests_before_the_full_run_and_can_stop_after_it():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert 'EVAL_MODE:-pipeline}" = "gen_only"' in text
    smoke = text.index("--smoke")
    assert smoke < text.index("for profile in $PROFILES")  # gate precedes the full sweep
    assert "SMOKE_ONLY" in text


def _exported(job: str, name: str) -> str:
    line = next(
        line for line in (SCRIPTS / job).read_text().splitlines() if f"export {name}=" in line
    )
    return line.split("=", 1)[1].strip('"')


def test_the_job_body_takes_max_model_len_from_the_environment_defaulting_to_8192():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert '--max-model-len "${MAX_MODEL_LEN:-8192}"' in text  # pipeline jobs unchanged


@pytest.mark.parametrize("job", GENONLY_JOBS)
def test_each_bakeoff_job_sets_a_context_length_that_fits_its_longest_prompt(job):
    # vLLM rejects a request whose prompt plus max_tokens exceeds --max-model-len.
    # Measured with the four models' tokenizers: the longest prompt is omnisql's,
    # 2253 tokens, so 2253 + 2048 = 4301. Here, without a tokenizer, the prompt is
    # bounded at 2.5 chars/token (measured: 2.9), which still has to fit.
    from evals import gen_prompts
    from evals.gen_only_eval import DEFAULT_MAX_TOKENS
    from evals.passn_scoring import GOLD_PATH, load_jsonl
    from ledgerql import schema_index
    from tests.support import require_fixture

    db = str(require_fixture("tests/fixtures/eval_fixture.duckdb"))
    schema, context = gen_prompts.introspect(db), schema_index.get_schema_context()
    chars = max(
        len(m["content"])
        for profile in gen_prompts.PROFILES
        for case in load_jsonl(GOLD_PATH)
        for m in gen_prompts.build_messages(
            profile, case["question"], schema=schema, schema_context=context
        )
    )
    context_len = int(_exported(job, "MAX_MODEL_LEN"))
    assert context_len >= chars / 2.5 + DEFAULT_MAX_TOKENS
    assert context_len <= 8192  # never back toward the default that overflowed the KV cache


def test_each_job_writes_its_own_vllm_logs_so_concurrent_jobs_do_not_overwrite_them():
    # Four bake-off jobs shared one vllm_server.err in the checkout; the failed
    # job's server log was unrecoverable. Names carry the SLURM job id.
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert "vllm_server_${SLURM_JOB_ID:-manual}.err" in text
    assert "> vllm_server.out" not in text and "cat vllm_server.err" not in text


def test_a_failed_smoke_test_prints_the_server_log_tail_before_the_job_exits():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    smoke = text.index("--smoke 3")
    assert 'tail -n 80 "$VLLM_ERR"' in text[smoke:]
    assert "PIPESTATUS" in text[smoke:]  # the smoke exit code survives the tee


ENTITYLINK_JOBS = {
    "run_qwen3_coder_30b_entitylink.sbatch": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "run_xiyansql_32b_entitylink.sbatch": "XGenerationLab/XiYanSQL-QwenCoder-32B-2504",
}


@pytest.mark.parametrize("job,repo_id", ENTITYLINK_JOBS.items())
def test_each_entity_link_job_runs_the_ddl_prompt_with_and_without_linking(job, repo_id):
    text = (SCRIPTS / job).read_text()
    assert "export EVAL_MODE=gen_only" in text
    assert _exported(job, "PROFILES") == "omnisql"  # the DDL prompt, only
    assert _exported(job, "ENTITY_LINK_AB") == "1"
    assert _exported(job, "MAX_MODEL_LEN") == "5120"
    assert "${GOLD_FILE:-evals/gold_v3.jsonl}" in text  # frozen v3 by default; held-out by override
    assert f"run_model_eval.sh {repo_id} 1" in text
    assert "--gres=gpu:h100-80:1" in text


def test_the_ab_job_runs_each_profile_unlinked_then_linked_in_one_server_session():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    body = text[text.index("for profile in $PROFILES") :]
    plain = body.index('--out "$OUT" --gold')
    linked = body.index("--entity-link")
    assert plain < linked  # same server, same seeds, baseline first
    assert "ENTITY_LINK_AB" in body
    assert text.index("--smoke") < text.index(
        "for profile in $PROFILES"
    )  # the gate still comes first
    assert '--gold "$GOLD_FILE"' in text


def test_the_pipeline_job_scores_against_the_frozen_gold_unless_told_otherwise():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    start = text.index("uv run python evals/run_eval.py")
    command = text[start : text.index("\nfi", start)]  # the invocation, with its continuation
    assert '--gold "${GOLD_FILE:-evals/gold_v3.jsonl}"' in command


def test_the_pipeline_job_records_the_entity_linking_setting_it_ran_with():
    # The pipeline reads LEDGERQL_ENTITY_LINK from the environment and the job does not set it, so
    # a run made with the wrong setting would look like any other. It is printed and recorded.
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert '"entity_link": "${LEDGERQL_ENTITY_LINK:-}"' in text
    pipeline_branch = text[text.index("Running eval with LLM_BACKEND=vllm") :]
    assert "LEDGERQL_ENTITY_LINK" in pipeline_branch.splitlines()[0]
    # ... and the submitting shell's value reaches the job
    assert "--export=ALL,EXPECTED_COMMIT=" in (SCRIPTS / "submit.sh").read_text()


def test_the_job_body_never_hard_codes_port_8000_because_jobs_share_nodes():
    """Jobs 47314848 and 47314850 ran on one node: XiYan's smoke requests were answered by the
    30B's server (404, wrong model) and the 30B pipeline job's own server failed to bind
    ("Address already in use") and ran against another job's server until it exited."""
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert "8000" not in text
    assert "$PORT" in text
    assert '--port "$PORT"' in text
    assert "http://localhost:$PORT" in text


def test_the_job_picks_a_free_port_and_checks_the_server_it_reaches_is_its_own_model():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert "pick_free_port" in text
    probe = text.index("PORT=$(pick_free_port")
    serve = text.index('"$VLLM_PYTHON/vllm" serve')
    assert probe < serve  # the port is chosen before the server is started
    ready = text.index("vllm is ready.")
    identity = text.index("/v1/models")
    smoke = text.index("--smoke")
    assert ready < identity < smoke  # identity is checked after readiness and before any request
    assert (
        '"$REPO_ID"' in text[identity : identity + 300]
        or "$REPO_ID" in text[identity : identity + 300]
    )
    assert "exit 1" in text[identity : identity + 700]  # a mismatch stops the job


def test_the_pipeline_job_exports_the_chosen_port_to_the_pipeline_client():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    start = text.index("uv run python evals/run_eval.py")
    assert 'VLLM_HOST="http://localhost:$PORT"' in text[start - 200 : start + 50]


def test_pick_free_port_returns_a_bindable_port_and_two_calls_can_differ(tmp_path):
    import re
    import socket

    text = (SCRIPTS / "run_model_eval.sh").read_text()
    fn = re.search(r"pick_free_port\(\) \{.*?\n\}", text, re.S).group(0)
    script = tmp_path / "t.sh"
    script.write_text(fn + "\npick_free_port\n")
    out = subprocess.run(["bash", str(script)], capture_output=True, text=True, check=True)
    port = int(out.stdout.strip())
    assert 1024 < port < 65536
    s = socket.socket()
    s.bind(("0.0.0.0", port))  # it really is free
    s.close()


def _job_text() -> str:
    return (SCRIPTS / "run_model_eval.sh").read_text()


def test_the_job_reads_its_environment_before_any_gpu_work_and_a_failed_read_does_not_stop_it(
    tmp_path,
):
    text = _job_text()
    read = text.index('RUN_ENV="$(uv run python -m evals.run_env')
    assert read < text.index('"$VLLM_PYTHON/vllm" serve')  # before the server is started
    assert '--server-python "$VLLM_PYTHON/python"' in text[read : read + 200]
    # the two lines as the job runs them, with a `uv` that fails, under the job's own `set -e`
    lines = text[read : text.index("\n", text.index("|| RUN_ENV=", read))]
    (tmp_path / "uv").write_text("#!/bin/bash\nexit 1\n")
    (tmp_path / "uv").chmod(0o755)
    script = f'set -euo pipefail\nVLLM_PYTHON=/none\n{lines}\necho "$RUN_ENV"\n'
    done = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        env={**ENV, "PATH": f"{tmp_path}:{ENV['PATH']}"},
    )
    assert done.returncode == 0 and "unavailable" in json.loads(done.stdout)


def test_run_meta_is_valid_json_and_carries_the_environment_the_job_read():
    text = _job_text()
    start = text.index('cat > "$OUT/run_meta.json" <<META')
    heredoc = text[start : text.index("\nMETA\n", start) + len("\nMETA\n")]
    env_json = json.dumps({"packages": {"duckdb": "1.5.5"}, "server": {"vllm": "0.29.0"}}, indent=2)
    script = (
        'OUT=/dev; EXPECTED_COMMIT=abc; REPO_ID="org/model"; TP_SIZE=1; PORT=1234\n'
        f"RUN_ENV='{env_json}'\n" + heredoc.replace('"$OUT/run_meta.json"', "/dev/stdout")
    )
    done = subprocess.run(["bash", "-c", script], capture_output=True, text=True, env=ENV)
    meta = json.loads(done.stdout)
    assert meta["environment"]["server"]["vllm"] == "0.29.0"
    assert meta["environment"]["packages"]["duckdb"] == "1.5.5"
    assert meta["model"] == "org/model" and meta["tensor_parallel_size"] == 1


# --- nothing a held-out run depends on is left to the submitting shell or to "whatever is current"

PINNED_JOBS = sorted(
    p.name for p in SCRIPTS.glob("*.sbatch") if p.name != "run_omnisql_32b_genonly.sbatch"
)
# The variables the job body reads with a default that a job file does not have to set, and why.
NOT_SET_BY_THE_JOB_FILE = {
    "GOLD_FILE": "the submission's choice: which gold the run is scored against",
    "SMOKE_ONLY": "the submission's choice: stop after the smoke test",
    "LEDGERQL_ENTITY_LINK": "checked against configuration H by the run itself",
    "EXPECTED_COMMIT": "given by submit.sh",
    "LOCAL": "set by the cluster",
    "SLURM_JOB_ID": "set by the cluster",
    "PORT": "picked by the job",
    "smoke_status": "set by the job",
}


def test_the_pinned_job_files_are_the_ones_the_measurement_pin_lists():
    from evals import measurement_pin

    assert PINNED_JOBS == sorted(
        Path(rel).name for rel in measurement_pin.PINNED if rel.endswith(".sbatch")
    )


@pytest.mark.parametrize("job", PINNED_JOBS)
def test_a_pinned_job_file_sets_every_variable_the_job_body_would_otherwise_inherit(job):
    # submit.sh exports the submitting shell's whole environment to the job. A variable the job
    # body reads with a default (the context length, extra server flags, the mode) and the job file
    # does not set is whatever that shell happened to hold.
    import re

    read = set(re.findall(r"\$\{([A-Za-z_]+):[-?]", _job_text()))
    job_level = read - set(NOT_SET_BY_THE_JOB_FILE)
    assert job_level == {
        "EVAL_MODE",
        "MAX_MODEL_LEN",
        "VLLM_EXTRA_ARGS",
        "PROFILES",
        "ENTITY_LINK_AB",
    }
    text = (SCRIPTS / job).read_text()
    for name in sorted(job_level):
        lines = [x for x in text.splitlines() if x.startswith(f"export {name}=")]
        assert len(lines) == 1, (job, name)
        assert "$" not in lines[0], (job, name)  # a literal, never the inherited value


@pytest.mark.parametrize(
    "job", ["run_qwen3_coder_30b_fp16.sbatch", "run_qwen25_coder_32b_awq.sbatch"]
)
def test_the_pipeline_jobs_state_the_job_bodys_defaults_in_the_file(job):
    assert _exported(job, "EVAL_MODE") == "pipeline"
    assert _exported(job, "MAX_MODEL_LEN") == "8192"  # the job body's default
    assert _exported(job, "VLLM_EXTRA_ARGS") == ""
    assert _exported(job, "PROFILES") == "" and _exported(job, "ENTITY_LINK_AB") == ""


def test_run_meta_records_how_the_model_was_served():
    text = _job_text()
    assert '"max_model_len": "${MAX_MODEL_LEN:-8192}"' in text
    assert '"vllm_extra_args": "${VLLM_EXTRA_ARGS:-}"' in text


def test_every_scored_run_tells_the_eval_which_interpreter_serves_the_model():
    # a held-out run is refused unless the server's versions are the pinned ones, and the eval
    # reads them through the interpreter of the environment that `vllm serve` was started from
    text = _job_text()
    assert 'VLLM_PYTHON="$ROOT/vllm-env/.venv/bin"' in text and '"$VLLM_PYTHON/vllm" serve' in text
    commands = text.split("uv run python ")[1:]
    scored = [
        c[: c.index("\n    fi") if "\n    fi" in c else None]
        for c in commands
        if "--gold" in c.split("\n\n")[0]
    ]
    assert len(scored) == 3  # gen-only, gen-only linked, the pipeline
    for command in scored:
        invocation = command.split("\n\n")[0]
        assert '--server-python "$VLLM_PYTHON/python"' in invocation, invocation


def _vllm_block() -> str:
    text = (SCRIPTS / "setup_env.sh").read_text()
    start = text.index("# --- vLLM's own separate venv ---")
    return text[start : text.index('echo "vLLM version:', start)]


def _run_vllm_block(tmp_path, installed: str | None):
    """The vLLM part of setup_env.sh as written, against a fake `uv` that records its arguments
    and, if `installed` is given, an existing environment holding that version."""
    env_dir = tmp_path / "vllm-env"
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    (bin_dir / "uv").write_text(f'#!/bin/bash\necho "$@" >> {tmp_path}/uv.log\n')
    (bin_dir / "uv").chmod(0o755)
    if installed is not None:
        venv_bin = env_dir / ".venv/bin"
        venv_bin.mkdir(parents=True)
        for name, body in (("vllm", "exit 0"), ("python", f"echo {installed}")):
            (venv_bin / name).write_text(f"#!/bin/bash\n{body}\n")
            (venv_bin / name).chmod(0o755)
    script = f"set -euo pipefail\nVLLM_ENV_DIR={env_dir}\nPY_INTERP=python3\n{_vllm_block()}"
    done = subprocess.run(
        ["bash", "-c", script],
        capture_output=True,
        text=True,
        env={**ENV, "PATH": f"{bin_dir}:{ENV['PATH']}"},
    )
    log = tmp_path / "uv.log"
    return done, log.read_text() if log.exists() else ""


def test_setup_installs_the_named_vllm_version_not_whatever_is_current(tmp_path):
    done, uv_log = _run_vllm_block(tmp_path, installed=None)
    assert done.returncode == 0, done.stderr
    assert "pip install" in uv_log and "vllm==0.29.0" in uv_log


def test_setup_leaves_an_environment_that_holds_the_named_version_alone(tmp_path):
    done, uv_log = _run_vllm_block(tmp_path, installed="0.29.0")
    assert done.returncode == 0 and uv_log == ""
    assert "0.29.0" in done.stdout


def test_setup_stops_on_an_environment_that_holds_another_version(tmp_path):
    done, uv_log = _run_vllm_block(tmp_path, installed="0.30.1")
    assert done.returncode == 1 and uv_log == ""  # it says so and changes nothing
    assert "0.30.1" in done.stderr and "0.29.0" in done.stderr
