import re
from pathlib import Path

import pytest

from tests.support import require_fixture


def test_a_missing_fixture_fails_loudly_and_names_the_path(tmp_path):
    with pytest.raises(pytest.fail.Exception) as excinfo:
        require_fixture(tmp_path / "absent.jsonl")
    message = str(excinfo.value)
    assert "absent.jsonl" in message
    assert "not skipped" in message  # says why this is a failure and not a skip


def test_an_existing_fixture_is_returned_unchanged(tmp_path):
    f = tmp_path / "there.jsonl"
    f.write_text("{}")
    assert require_fixture(f) == f


def test_no_test_that_reads_a_bridges2_report_may_skip_when_it_is_missing():
    # A test that skips on a missing fixture reports green for a reason unrelated
    # to whether it passes: on a fresh clone the "reproduces the report exactly"
    # tests silently did nothing, and the derived figures they guarded could not
    # be regenerated by anyone. Guard the whole class, not just today's files.
    offenders = []
    for path in Path("tests").glob("test_*.py"):
        if path.name == "test_support.py":
            continue
        text = path.read_text()
        if "eval_bridges2" in text and re.search(r"pytest\.skip\(|skipif\(|importorskip\(", text):
            offenders.append(path.name)
    assert offenders == [], f"skip on a missing Bridges-2 fixture: {offenders}"
