"""The Bridges-2 runbook's hard stops, exercised against real git repos.

The incident these guard: `git pull` aborted (a tracked report had local changes
from a previous run), HEAD stayed on an old commit, the hash check printed the
mismatch -- and the sbatch lines ran anyway, so both jobs ran the wrong code. A
check that only works when a human is reading the output fails exactly when they
are moving fast, so every check here must stop the script, not just print.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

SCRIPTS = Path("scripts/bridges2").resolve()
ENV = {
    **os.environ,
    "GIT_AUTHOR_NAME": "t",
    "GIT_AUTHOR_EMAIL": "t@t",
    "GIT_COMMITTER_NAME": "t",
    "GIT_COMMITTER_EMAIL": "t@t",
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
}


def git(cwd: Path, *args: str) -> str:
    out = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True, env=ENV
    )
    return out.stdout.strip()


def commit(repo: Path, name: str, text: str) -> str:
    (repo / name).parent.mkdir(parents=True, exist_ok=True)
    (repo / name).write_text(text)
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", f"add {name}")
    return git(repo, "rev-parse", "HEAD")


@pytest.fixture
def cluster(tmp_path):
    """origin (bare) at H2, a laptop clone that pushed both commits, and a
    'cluster' clone that only ever pulled H1 -- the stale checkout."""
    origin = tmp_path / "origin.git"
    subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True, env=ENV)
    laptop = tmp_path / "laptop"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(laptop)], check=True, env=ENV, capture_output=True
    )
    git(laptop, "checkout", "-q", "-b", "main")
    # The job runs assert_commit.sh from inside the checkout it verifies, so a
    # real checkout contains it; the fake one must too.
    (laptop / "scripts/bridges2").mkdir(parents=True)
    (laptop / "scripts/bridges2/assert_commit.sh").write_text(
        (SCRIPTS / "assert_commit.sh").read_text()
    )
    for job in SCRIPTS.glob("*.sbatch"):  # submit.sh refuses a job file the checkout lacks
        (laptop / "scripts/bridges2" / job.name).write_text(job.read_text())
    h1 = commit(laptop, "reports/eval.md", "v1\n")
    git(laptop, "push", "-q", "origin", "main")
    stale = tmp_path / "stale"
    subprocess.run(
        ["git", "clone", "-q", str(origin), str(stale)], check=True, env=ENV, capture_output=True
    )
    h2 = commit(laptop, "code.py", "print(2)\n")
    git(laptop, "push", "-q", "origin", "main")
    return {
        "stale": stale,
        "h1": h1,
        "h2": h2,
        "calls": tmp_path / "sbatch_calls.txt",
        "tmp": tmp_path,
    }


def stub_sbatch(tmp: Path, calls: Path) -> Path:
    stub = tmp / "sbatch"
    stub.write_text(f'#!/bin/bash\necho "$@" >> {calls}\n')
    stub.chmod(0o755)
    return stub


def run_submit(cluster, expected: str | None, *jobs: str):
    stub = stub_sbatch(cluster["tmp"], cluster["calls"])
    args = ["bash", str(SCRIPTS / "submit.sh")] + ([expected, *jobs] if expected else [])
    env = {**ENV, "LEDGERQL_REPO": str(cluster["stale"]), "SBATCH": str(stub)}
    return subprocess.run(args, capture_output=True, text=True, env=env)


def sbatch_calls(cluster) -> list[str]:
    return cluster["calls"].read_text().splitlines() if cluster["calls"].exists() else []


def test_submit_stops_before_sbatch_when_a_tracked_file_blocks_the_pull(cluster):
    # THE INCIDENT: a previous run left reports/eval.md modified; pull aborts.
    (cluster["stale"] / "reports/eval.md").write_text("regenerated by an old run\n")
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []  # nothing was submitted
    assert "reports/eval.md" in result.stderr
    assert "git checkout -- reports/eval.md" in result.stderr  # the recovery command
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h1"]  # untouched


def test_submit_stops_before_sbatch_when_head_is_not_the_expected_commit(cluster):
    wrong = "0" * 40
    result = run_submit(cluster, wrong)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "MISMATCH" in result.stderr and "git pull" in result.stderr


def test_submit_pulls_verifies_and_submits_both_jobs_pinned_to_the_commit(cluster):
    result = run_submit(cluster, cluster["h2"])
    assert result.returncode == 0, result.stderr
    assert git(cluster["stale"], "rev-parse", "HEAD") == cluster["h2"]
    calls = sbatch_calls(cluster)
    assert len(calls) == 2
    assert all(f"EXPECTED_COMMIT={cluster['h2']}" in c for c in calls)
    assert any("30b" in c for c in calls) and any("32b" in c for c in calls)


def test_submit_takes_an_explicit_job_list_and_pins_each_to_the_commit(cluster):
    stale = cluster["stale"]
    laptop_job = "run_bakeoff_a.sbatch"
    # The job files must exist in the pulled commit, so add them upstream first.
    origin = git(stale, "remote", "get-url", "origin")
    laptop = cluster["tmp"] / "laptop"
    for name in (laptop_job, "run_bakeoff_b.sbatch"):
        h = commit(laptop, f"scripts/bridges2/{name}", "#!/bin/bash\n")
    git(laptop, "push", "-q", origin, "main")
    result = run_submit(cluster, h, laptop_job, "run_bakeoff_b.sbatch")
    assert result.returncode == 0, result.stderr
    calls = sbatch_calls(cluster)
    assert len(calls) == 2
    assert all(f"EXPECTED_COMMIT={h}" in c for c in calls)
    assert calls[0].endswith(laptop_job) and calls[1].endswith("run_bakeoff_b.sbatch")


def test_submit_submits_nothing_if_any_named_job_file_is_missing(cluster):
    # One typo must not leave the first job submitted and the second not.
    result = run_submit(cluster, cluster["h2"], "run_does_not_exist.sbatch")
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "run_does_not_exist.sbatch" in result.stderr


def test_submit_refuses_to_run_without_an_expected_commit(cluster):
    result = run_submit(cluster, None)
    assert result.returncode != 0
    assert sbatch_calls(cluster) == []
    assert "usage" in result.stderr.lower()  # refused for the right reason


def test_submit_refuses_an_abbreviated_hash(cluster):
    # A short prefix could match the wrong commit; the runbook needs all 40.
    result = run_submit(cluster, cluster["h2"][:7])
    assert result.returncode != 0 and sbatch_calls(cluster) == []
    assert "40" in result.stderr


def test_assert_commit_passes_only_on_the_exact_clean_commit(cluster):
    repo = cluster["stale"]
    ok = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert ok.returncode == 0 and cluster["h1"] in ok.stdout
    (repo / "reports/eval.md").write_text("dirty\n")
    dirty = subprocess.run(
        ["bash", str(SCRIPTS / "assert_commit.sh"), cluster["h1"], str(repo)],
        capture_output=True,
        text=True,
        env=ENV,
    )
    assert dirty.returncode != 0 and "reports/eval.md" in dirty.stderr


def test_the_job_itself_refuses_to_start_without_or_on_the_wrong_commit(cluster, tmp_path):
    # Belt and braces: even if someone runs sbatch by hand and skips submit.sh,
    # the job must refuse. Guard runs before any module load / GPU work.
    home = tmp_path / "home"
    (home / "ledgerql-bridges2").mkdir(parents=True)
    (home / "ledgerql-bridges2" / "ledgerql").symlink_to(cluster["stale"])
    script = [str(SCRIPTS / "run_model_eval.sh"), "some/model", "1"]
    env = {**ENV, "HOME": str(home)}
    env.pop("EXPECTED_COMMIT", None)
    missing = subprocess.run(["bash", *script], capture_output=True, text=True, env=env)
    assert missing.returncode != 0 and "EXPECTED_COMMIT" in missing.stderr
    wrong = subprocess.run(
        ["bash", *script], capture_output=True, text=True, env={**env, "EXPECTED_COMMIT": "0" * 40}
    )
    assert wrong.returncode != 0 and "MISMATCH" in wrong.stderr
    right = subprocess.run(
        ["bash", *script],
        capture_output=True,
        text=True,
        env={**env, "EXPECTED_COMMIT": cluster["h1"]},
    )
    assert "commit verified" in right.stdout  # got past the guard (then fails on module load)


GENONLY_JOBS = {
    "run_qwen3_coder_30b_genonly.sbatch": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "run_qwen25_coder_32b_awq_genonly.sbatch": "Qwen/Qwen2.5-Coder-32B-Instruct-AWQ",
    "run_xiyansql_32b_genonly.sbatch": "XGenerationLab/XiYanSQL-QwenCoder-32B-2504",
    "run_omnisql_32b_genonly.sbatch": "seeklhy/OmniSQL-32B",
}


def test_every_bridges2_script_parses():
    for script in [*SCRIPTS.glob("*.sh"), *SCRIPTS.glob("*.sbatch")]:
        result = subprocess.run(["bash", "-n", str(script)], capture_output=True, text=True)
        assert result.returncode == 0, f"{script.name}: {result.stderr}"


@pytest.mark.parametrize("job,repo_id", GENONLY_JOBS.items())
def test_each_bakeoff_job_runs_the_generation_only_mode_for_its_model(job, repo_id):
    text = (SCRIPTS / job).read_text()
    assert "export EVAL_MODE=gen_only" in text
    assert "export PROFILES=" in text
    assert f"run_model_eval.sh {repo_id} 1" in text
    assert "--gres=gpu:h100-80:1" in text  # H100-80 (docs/bridges2.md), not the V100 pool


def test_a_bakeoff_model_runs_its_own_native_profile_first_so_the_smoke_tests_it():
    def profiles(job):
        line = next(
            line for line in (SCRIPTS / job).read_text().splitlines() if "export PROFILES=" in line
        )
        return line.split("=", 1)[1].strip('"').split()

    assert profiles("run_xiyansql_32b_genonly.sbatch")[0] == "xiyan"
    assert profiles("run_omnisql_32b_genonly.sbatch")[0] == "omnisql"
    for job in ("run_qwen3_coder_30b_genonly.sbatch", "run_qwen25_coder_32b_awq_genonly.sbatch"):
        assert profiles(job)[0] == "current"
    assert all(set(profiles(j)) == {"current", "xiyan", "omnisql"} for j in GENONLY_JOBS)


def test_the_job_body_smoke_tests_before_the_full_run_and_can_stop_after_it():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert 'EVAL_MODE:-pipeline}" = "gen_only"' in text
    smoke = text.index("--smoke")
    assert smoke < text.index("for profile in $PROFILES")  # gate precedes the full sweep
    assert "SMOKE_ONLY" in text


def _exported(job: str, name: str) -> str:
    line = next(
        line for line in (SCRIPTS / job).read_text().splitlines() if f"export {name}=" in line
    )
    return line.split("=", 1)[1].strip('"')


def test_the_job_body_takes_max_model_len_from_the_environment_defaulting_to_8192():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert '--max-model-len "${MAX_MODEL_LEN:-8192}"' in text  # pipeline jobs unchanged


@pytest.mark.parametrize("job", GENONLY_JOBS)
def test_each_bakeoff_job_sets_a_context_length_that_fits_its_longest_prompt(job):
    # vLLM rejects a request whose prompt plus max_tokens exceeds --max-model-len.
    # Measured with the four models' tokenizers: the longest prompt is omnisql's,
    # 2253 tokens, so 2253 + 2048 = 4301. Here, without a tokenizer, the prompt is
    # bounded at 2.5 chars/token (measured: 2.9), which still has to fit.
    from evals import gen_prompts
    from evals.gen_only_eval import DEFAULT_MAX_TOKENS
    from evals.passn_scoring import GOLD_PATH, load_jsonl
    from ledgerql import schema_index
    from tests.support import require_fixture

    db = str(require_fixture("tests/fixtures/eval_fixture.duckdb"))
    schema, context = gen_prompts.introspect(db), schema_index.get_schema_context()
    chars = max(
        len(m["content"])
        for profile in gen_prompts.PROFILES
        for case in load_jsonl(GOLD_PATH)
        for m in gen_prompts.build_messages(
            profile, case["question"], schema=schema, schema_context=context
        )
    )
    context_len = int(_exported(job, "MAX_MODEL_LEN"))
    assert context_len >= chars / 2.5 + DEFAULT_MAX_TOKENS
    assert context_len <= 8192  # never back toward the default that overflowed the KV cache


def test_each_job_writes_its_own_vllm_logs_so_concurrent_jobs_do_not_overwrite_them():
    # Four bake-off jobs shared one vllm_server.err in the checkout; the failed
    # job's server log was unrecoverable. Names carry the SLURM job id.
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    assert "vllm_server_${SLURM_JOB_ID:-manual}.err" in text
    assert "> vllm_server.out" not in text and "cat vllm_server.err" not in text


def test_a_failed_smoke_test_prints_the_server_log_tail_before_the_job_exits():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    smoke = text.index("--smoke 3")
    assert 'tail -n 80 "$VLLM_ERR"' in text[smoke:]
    assert "PIPESTATUS" in text[smoke:]  # the smoke exit code survives the tee


ENTITYLINK_JOBS = {
    "run_qwen3_coder_30b_entitylink.sbatch": "Qwen/Qwen3-Coder-30B-A3B-Instruct",
    "run_xiyansql_32b_entitylink.sbatch": "XGenerationLab/XiYanSQL-QwenCoder-32B-2504",
}


@pytest.mark.parametrize("job,repo_id", ENTITYLINK_JOBS.items())
def test_each_entity_link_job_runs_the_ddl_prompt_with_and_without_linking(job, repo_id):
    text = (SCRIPTS / job).read_text()
    assert "export EVAL_MODE=gen_only" in text
    assert _exported(job, "PROFILES") == "omnisql"  # the DDL prompt, only
    assert _exported(job, "ENTITY_LINK_AB") == "1"
    assert _exported(job, "MAX_MODEL_LEN") == "5120"
    assert "${GOLD_FILE:-evals/gold_v3.jsonl}" in text  # frozen v3 by default; held-out by override
    assert f"run_model_eval.sh {repo_id} 1" in text
    assert "--gres=gpu:h100-80:1" in text


def test_the_ab_job_runs_each_profile_unlinked_then_linked_in_one_server_session():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    body = text[text.index("for profile in $PROFILES") :]
    plain = body.index('--out "$OUT" --gold')
    linked = body.index("--entity-link")
    assert plain < linked  # same server, same seeds, baseline first
    assert "ENTITY_LINK_AB" in body
    assert text.index("--smoke") < text.index(
        "for profile in $PROFILES"
    )  # the gate still comes first
    assert '--gold "$GOLD_FILE"' in text


def test_the_pipeline_job_scores_against_the_frozen_gold_unless_told_otherwise():
    text = (SCRIPTS / "run_model_eval.sh").read_text()
    start = text.index("uv run python evals/run_eval.py")
    command = text[start : text.index("\nfi", start)]  # the invocation, with its continuation
    assert '--gold "${GOLD_FILE:-evals/gold_v3.jsonl}"' in command
